
    <?php

    use Ajrc\Helper\Sessions;
    use Ajrc\Helper\AlertBootstrap4 as Alert;
    use Ajrc\Model\Usuario;
    
    $u = Usuario::List(Sessions::UserID());
    
    if(empty($u)){
      echo "Usuário inexistente!";
      exit();
    }
    
    $check_excluir_foto = null;
    $foto_usuario = null;
    $pasta_imagens = "img/usuarios/";
    foreach (glob($pasta_imagens . $u->id."_1.*") as $foto) {
        $foto_usuario = "<img src='".$foto."'>";
        $check_excluir_foto =  '<br><div class="checkbox checkbox-success checkbox-inline">
                                    <input tabindex="18" name="excluir_foto" id="excluir_foto" value="'.$foto.'" type="checkbox">
                                    <label for="excluir_foto">Excluir a foto atual?</label>
                                </div>';
    }

    $sexo = null;
    $sexos = [""=>"Selecione", "M"=>"Masculino", "F"=>"Feminino"];
    foreach($sexos as $key=>$value){
        $sel = ($u->sexo==$key)?" selected='selected'":null;
        $sexo.= "<option value='".$key."'".$sel.">".$value."</option>";
    }
    

    $required = " required ";
    
      
    require_once("../templates/public/header.php");
    require_once("../templates/public/topo.php");

    ?>

    <!-- Main Content -->
    <div class="container my-3">
      <div class="row">

        <div class="col-md-4 col-lg-3">
          <div class="card">
            <div class="card-body text-center">
              <img src="<?php echo Sessions::UserPhoto(); ?>" width="80" height="80" alt="Foto de Adair" class="rounded-circle mb-3">
              <h5 class="bold mb-0"><?php echo Sessions::UserName(); ?></h5>
              <small class="counter">Cliente desde <?php echo Sessions::UserSince(); ?></small>
              <hr>
              <div class="roboto-condensed bold" data-toggle="tooltip" title="You currently have 1,113 Points to spend.">
                <i data-feather="award" class="text-warning"></i> Pontos: 1113</div>
            </div>
            <div class="list-group list-group-flush">
              <a href="./account-profile" class="list-group-item list-group-item-action"><i data-feather="user" class="mr-3"></i> Seus Dados</a>
              <a href="#account-orders" class="list-group-item list-group-item-action active"><i data-feather="shopping-bag" class="mr-3"></i> Pedidos</a>
              <a href="./account-wishlist" class="list-group-item has-badge list-group-item-action"><i data-feather="heart" class="mr-3"></i> Lista de Desejos <span class="badge rounded badge-primary">2</span></a>
              <a href="./account-logout" class="list-group-item list-group-item-action text-danger"><i data-feather="log-out" class="mr-3"></i> Logout</a>
            </div>
          </div>
        </div>

        <div class="col mt-3 mt-md-0">
          <div class="card">
            <div class="card-body">
              <h3>Meus Pedidos</h3><hr>
              <div class="table-responsive">
                <table class="table table-hover" data-addclass-on-xs="table-sm">
                  <thead class="thead-light">
                    <tr>
                      <th scope="col">Order ID</th>
                      <th scope="col">Date</th>
                      <th scope="col" class="text-right">Total</th>
                      <th scope="col" class="text-center">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="row"><a href="account-order-detail.html">ORD556789</a></th>
                      <td>Dec 19, 2017</td>
                      <td class="text-right">$74.00</td>
                      <td class="text-center"><span class="badge badge-warning rounded">In Progress</span></td>
                    </tr>
                    <tr>
                      <th scope="row"><a href="account-order-detail.html">ORD456789</a></th>
                      <td>Dec 10, 2017</td>
                      <td class="text-right">$100.00</td>
                      <td class="text-center"><span class="badge badge-danger rounded">Canceled</span></td>
                    </tr>
                    <tr>
                      <th scope="row"><a href="account-order-detail.html">ORD356789</a></th>
                      <td>Dec 01, 2017</td>
                      <td class="text-right">$20.00</td>
                      <td class="text-center"><span class="badge badge-success rounded">Finished</span></td>
                    </tr>
                    <tr>
                      <th scope="row"><a href="account-order-detail.html">ORD256789</a></th>
                      <td>Nov 19, 2017</td>
                      <td class="text-right">$74.00</td>
                      <td class="text-center"><span class="badge badge-success rounded">Finished</span></td>
                    </tr>
                    <tr>
                      <th scope="row"><a href="account-order-detail.html">ORD156789</a></th>
                      <td>Nov 10, 2017</td>
                      <td class="text-right">$100.00</td>
                      <td class="text-center"><span class="badge badge-success rounded">Finished</span></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
    <!-- /Main Content -->


    <!-- Footer -->
    <?php 
    require_once("../templates/public/footer.php"); 
    ?>
    <!-- /Footer -->
    


    <!-- REQUIRED JS  -->
    <script src="./plugins/jquery/jquery.min.js"></script>
    <script src="./plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="./plugins/feather-icons/feather.min.js"></script>
    <script src="./plugins/metismenu/metisMenu.min.js"></script>
    <script src="./plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>

    <!-- Mimity JS  -->
    <script src="./dist/js/script.min.js"></script>

    <script>
    $(function () {

      // Show reset password form
      $('.reset').click(function (event) {
        $('#row-login').attr('hidden', true)
        $('#row-reset').attr('hidden', false)
        event.preventDefault()
      })

      // Show login form
      $('.login').click(function (event) {
        $('#row-login').attr('hidden', false)
        $('#row-reset').attr('hidden', true)
        $('#row-reset-done').attr('hidden', true)
      })

      // Show reset password done message (demo purpose only)
      $('.reset-done').click(function (event) {
        $('#row-reset-done').attr('hidden', false)
        $('#row-reset').attr('hidden', true)
      })

    })
    </script>

  </body>
</html>