<?php

use Ajrc\Helper\Sessions;

if(!array_key_exists("id",$data)) { 
  header("location: ./notfound");
  exit();
}

// SEO : SEARCH ENGINE OPTIMIZATE ----
$title = "Chokoart - As CATEGORIAS de chocolates mais deliciosas que você verá e poderá provar!";
$description = $title." Chocolates de vários sabores para os mais refinados gostos!";
$url_redirect = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
//----

require_once("../templates/public/header.php");
require_once("../templates/public/topo.php");

$id_categoria = (int) $data["id"];

$orderby = null;
$ordernacaoAtual = "Ordenado - Aleatóriamente";
if(array_key_exists("order",$data)) { 
  if(stripos(trim($data["order"]), "mp-")!==false){ $orderby = "mp"; $ordernacaoAtual = "Ordenado - Menor Preço"; }
}

//----| LISTA AS CATEGORIAS NA LATERAL, APROVEITANDO A VARIÁVEL $categorias DO ARQUIVO topo.php |---- 
$CATEGORIA = null; 
$CATEGORIASMENULATERAL = null;
foreach($categorias as $c) {
  $sel = null;
  if($c->id==$id_categoria) { 
    $CATEGORIA = $c; $sel = ' class="mm-active"';
    $linkOrdRand =  './categoria-'.$c->id.'--'.str_replace(" ","-",$c->titulo);
    $linkOrdMenorPreco =  './categoria-'.$c->id.'-mp-'.str_replace(" ","-",$c->titulo);
  }
  $CATEGORIASMENULATERAL.='<li'.$sel.'><a href="./categoria-'.$c->id.'--'.str_replace(" ","-",$c->titulo).'" aria-expanded="true">'.$c->titulo.' <small class="counter">('.$c->total_produtos.')</small></a></li>';
}
//----

if($CATEGORIA==null) { 
  header("location: ./notfound?msg=de Categoria");
  exit(); 
}

?>

<!-- Main Content -->
<div class="container mt-3 mb-3">
      <div class="row gutters-3">

        <!-- Shop Filters -->
        <div class="col-lg-3 col-md-4">
          <div class="accordion accordion-caret accordion-sidebar d-none d-md-block">
            <div class="card">
              <div class="card-header">
                <a href="#filter-categories" data-toggle="collapse" aria-expanded="true" aria-controls="filter-categories" role="button" class="h6">
                  CATEGORIAS
                </a>
              </div>
              <div id="filter-categories" class="collapse show">
                <div class="card-body">
                  <ul class="list-tree">

                    <?php
                      //----| LISTA AS CATEGORIAS NA LATERAL |----
                      echo $CATEGORIASMENULATERAL;
                      //----
                    ?>

                  </ul>
                </div>
              </div>
            </div>
          </div>    
              
        </div>
        <!-- /Shop Filters -->

        <div class="col-lg-9 col-md-8">

          <!-- Shop Toolbar -->
          <div class="card mb-3">
            <div class="card-body d-flex justify-content-end align-items-center py-2">
              <button class="btn btn-sm btn-outline-primary rounded-pill d-block d-md-none mr-auto" data-toggle="modal" data-target="#filterModal"><i data-feather="filter"></i> Categorias</button>
              <ol class="breadcrumb d-none d-md-flex p-0 mb-0 mr-auto">
                <li class="breadcrumb-item"><a href="./">Página Principal</a></li>
                <li class="breadcrumb-item"><a href="#">Categorias</a></li>
                <li class="breadcrumb-item active" aria-current="page"><?php echo $CATEGORIA->titulo; ?></li>
              </ol>
              <div class="dropdown dropdown-hover">
                <button class="btn btn-light btn-sm border rounded-pill dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <?php echo $ordernacaoAtual; ?> <i data-feather="chevron-down"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right shadow-sm" aria-labelledby="dropdownMenuButton">
                  <button class="dropdown-item" type="button"><a href="<?php echo $linkOrdRand; ?>">Aleatória</a></button>
                  <button class="dropdown-item" type="button"><a href="<?php echo $linkOrdMenorPreco; ?>">Menor Preço</a></button>
                </div>
              </div>
            </div>
          </div>
          <!-- /Shop Toolbar -->

          <!-- Shop Grid -->
          <div class="grid grid-gap-3 grid-col-2 grid-col-lg-3 mt-3">
            <?php 
              //----| LISTA OS PRODUTOS DA CATEGORIA |------
              Ajrc\Model\Produto::GetPublicAll( $id_categoria, $orderby ); 
              //----
            ?>
          </div>
          <!-- /Shop Grid -->

          <!-- Shop Toolbar -->
          <div class="card mt-3">
            <div class="card-body d-flex justify-content-end align-items-center py-2">
              <button class="btn btn-sm btn-outline-primary rounded-pill d-block d-md-none mr-auto" data-toggle="modal" data-target="#filterModal"><i data-feather="filter"></i> Categorias</button>
              <ol class="breadcrumb d-none d-md-flex p-0 mb-0 mr-auto">
                <li class="breadcrumb-item"><a href="./">Página Principal</a></li>
                <li class="breadcrumb-item"><a href="#">Categorias</a></li>
                <li class="breadcrumb-item active" aria-current="page"><?php echo $CATEGORIA->titulo; ?></li>
              </ol>
              <div class="dropdown dropdown-hover">
                <button class="btn btn-light btn-sm border rounded-pill dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <?php echo $ordernacaoAtual; ?> <i data-feather="chevron-down"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right shadow-sm" aria-labelledby="dropdownMenuButton">
                <button class="dropdown-item" type="button"><a href="<?php echo $linkOrdRand; ?>">Ordenação - Aleatória</a></button>
                  <button class="dropdown-item" type="button"><a href="<?php echo $linkOrdMenorPreco; ?>">Ordenar - Menor Preço</a></button>
                </div>
              </div>
            </div>
          </div>
          <!-- /Shop Toolbar -->

        </div>
      </div>
    </div>
    <!-- /Main Content -->

    <!-- Filter Modal -->
    <div class="modal fade" id="filterModal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header border-bottom-0">
            <h5 class="modal-title">Categorias</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body p-0 pb-3">
                  <ul class="list-tree">

                    <?php
                      //----| LISTA AS CATEGORIAS NA LATERAL |----
                      echo $CATEGORIASMENULATERAL;
                      //----
                    ?>

                  </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- /Filter Modal -->

    


<!-- Footer -->
<?php 
require_once("../templates/public/footer.php"); 
?>
<!-- /Footer -->

    <script src="plugins/jquery/jquery.min.js"></script>
    <script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="plugins/feather-icons/feather.min.js"></script>
    <script src="plugins/metismenu/metisMenu.min.js"></script>
    <script src="plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="plugins/swiper/swiper.min.js"></script>
    <script src="plugins/nouislider/nouislider.min.js"></script>
    <script src="plugins/photoswipe/photoswipe.min.js"></script>
    <script src="plugins/photoswipe/photoswipe-ui-default.min.js"></script>
    <script src="plugins/noty/noty.min.js"></script>
    <script src="dist/js/script.min.js"></script>
    <script src="js/produto.js"></script>
    <script>
    $(function () {

      App.rating()
      App.atwDemo()
      App.colorOption()
      App.rating()
      App.quickviewDemo()

      var filter = {
        categories: function () {
          $('.list-tree').metisMenu()
        }
      }


     

      <?php
        if(Sessions::UserID()!="") { 
            echo "WishList.Persistence('../add-whislist');"; 
        }
        ?>

    })
    </script>




</body>
</html>
