    <?php

      use Ajrc\Helper\Sessions;
      use Ajrc\Helper\AlertBootstrap4 as Alert;
      
      // SEO : SEARCH ENGINE OPTIMIZATE ----
      $title = "Chokoart :: Fale Conosco!";
      $description = $title;
      $url_redirect = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
      //----
      
      require_once("../templates/public/header.php");
      require_once("../templates/public/topo.php");

      $msg = null;
      if(array_key_exists("msg",$data)) {
        $alert = ($data["status"]==200)?"success":"danger";
        $msg = Alert::get($alert, trim($data["msg"]), 8000);
      }


    ?>

    <!-- Main Content -->
    <div class="container my-3">
      <div class="card">
        <div class="card-body">
          <div class="row">

            <!-- Map -->
            <div class="col-md-6">
              <div class="img-thumbnail">
                <div class="embed-responsive embed-map">
                  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3021.9264094650316!2d-73.97488578459351!3d40.763643279326224!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c258f00eb25f59%3A0x75ddbee78904e799!2s767+5th+Ave%2C+New+York%2C+NY+10153%2C+USA!5e0!3m2!1sen!2sid!4v1532319134271" width="600" height="450" style="border:0" allowfullscreen></iframe>
                </div>
              </div>
            </div>

            <!-- Contact Us Form -->
            <div class="col-md-6 mt-3 mt-md-0">
              <h3 class="bold">Fale Conosco</h3>
              <?php
                echo $msg;
              ?>
              <form id="frmContato" data-toggle="validator" data-disable="false" role="form" class="mt-3 form-style-1" method="POST" action="./contate-nos">
                <div class="form-row">
                  <div class="form-group col-md-6">
                    <div class="media">
                      <div class="media-body ml-1">
                        <h5 class="bold">Endereço</h5>
                        <div>Rua X, 123 - Alto da Bela Vista</div>
                        <div>Cachoeira Paulista - CEP: 12630-000</div>
                      </div>
                    </div>
                  </div>
                  <div class="form-group col-md-6">
                    <h5 class="bold">Contatos</h5>
                    <div class="media mb-3 mb-md-0">
                      <span><i data-feather="phone"></i></span>
                      <div class="media-body ml-1">(12) 3131-3131</div>
                    </div>
                    <div class="media">
                      <span><i data-feather="mail"></i></span>
                      <div class="media-body ml-1">contato@chokoart.com.br</div>
                    </div>
                  </div>
                </div>
                <div id="rsmsg"></div>
                <div class="form-group">
                  <span class="input-icon">
                    <i data-feather="user"></i>
                    <input data-error="Campo de preenchimento obrigatório!" type="text" class="form-control" id="nome" name="nome" placeholder="Seu nome" required>
                  </span>
                  <div class="help-block with-errors"></div>
                </div>
                <div class="form-group">
                  <span class="input-icon">
                    <i data-feather="mail"></i>
                    <input data-error="Campo de preenchimento obrigatório!" type="email" id="email" name="email" class="form-control" placeholder="Seu e-mail" required>
                  </span>
                  <div class="help-block with-errors"></div>
                </div>
                <div class="form-group">
                  <span class="input-icon">
                    <i data-feather="message-square"></i>
                    <textarea data-error="Campo de preenchimento obrigatório!" class="form-control" rows="3" id="mensagem" name="mensagem" placeholder="Digite aqui sua mensagem!" required></textarea>
                  </span>
                  <div class="help-block with-errors"></div>
                </div>
                <button id="btnEnviarContato" type="submit" class="btn btn-primary">Enviar</button>
              </form>
            </div>
            <!-- /Contact Us Form -->

          </div>
        </div>
      </div>
    </div>
    <!-- /Main Content -->



    <!-- Footer -->
    <?php 
    require_once("../templates/public/footer.php"); 
    ?>
    <!-- /Footer -->

    <script src="./plugins/jquery/jquery.min.js"></script>
    <script src="./plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="./plugins/feather-icons/feather.min.js"></script>
    <script src="./plugins/metismenu/metisMenu.min.js"></script>
    <script src="./plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="./libs/bootstrap-validator/validator.min.js"></script>
    <script src="./dist/js/script.min.js"></script>

    <script>
    $(function () {
      $('input#nome').focus()
      $('button#btnEnviarContato').click(function(event) {
        event.preventDefault()
        $('button#btnEnviarContato').attr("disabled", true);
        $.ajax({
            type: "POST", url: './contate-nos', data: $("form#frmContato").serialize(),
            success: function(rs){ 
              $('input#nome').val('')
              $('input#email').val('')
              $('input#mensagem').val('')
              $('button#btnEnviarContato').removeAttr("disabled");
              var rsmsg = "<div class=\"alert alert-success\" role=\"alert\">"+rs+" <button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button></div>"
              
              $("div#rsmsg").html(rsmsg)
            },
            error: function(rs, status, err){ console.log('Erro --> ',rs , err) }
        });

        

      })

      App.atwDemo() // Add to Wishlist Demo
      <?php
        if(Sessions::UserID()!="") { 
          echo "WishList.Persistence('./add-whislist');"; 
        }
      ?>

    })
    </script>

  </body>
</html>