<?php

use Ajrc\Helper\Sessions;
use Ajrc\Helper\AlertBootstrap4 as Alert;
use Ajrc\Model\Destaque;
use Ajrc\Model\Produto;
use Ajrc\Config\ConfigPagSeguro as PagSeguro;

$title = "CheckOut Transparente - PagSeguro ";

require_once("../templates/public/header.php");
require_once("../templates/public/topo.php");

?>


    <!-- Main Content -->
    <div class="container my-3">

        <div class="card">
            <div class="card-header bg-white border-bottom flex-center p-0">
                <ul class="nav nav-pills card-header-pills main-nav-pills" role="tablist">
                    <li class="nav-item"><a class="nav-link" href="#">CARRINHO</a></li>
                    <li class="nav-item"><a class="nav-link disabled" href="javascript:void(0)"><i data-feather="arrow-right"></i></a></li>
                    <li class="nav-item"><a class="nav-link" href="#">ENTREGA</a></li>
                    <li class="nav-item"><a class="nav-link disabled" href="javascript:void(0)"><i data-feather="arrow-right"></i></a></li>
                    <li class="nav-item"><a class="nav-link active" href="#">PAGAMENTO</a></li>
                </ul>
            </div>

            <div class="card-body pt-5 flex-center flex-column">

                <h2 class="roboto-condensed">SEU CARRINHO</h2>
                <h6 class="text-muted mb-4">confira os itens abaixo</h6>
                <table class="table table-borderless table-cart" data-addclass-on-smdown="table-sm">
                    <tbody>
                        <tr>
                            <td class="cart-img nostretch">
                            <a href="shop-single.html"><img src="../img/products/1_small.jpg" alt="Hanes Hooded Sweatshirt"></a>
                            </td>
                            <td class="cart-title">
                            <a href="shop-single.html" class="h6 bold d-inline-block" title="Hanes Hooded Sweatshirt">Hanes Hooded Sweatshirt</a>
                            <div><i data-feather="check-circle" class="text-success"></i> In Stock</div>
                            
                            <small class="ml-3"><b>Size</b>: small</small>
                            
                            </td>
                            <td class="cart-qty nostretch text-center">
                            <div class="spinner" data-addclass-on-smdown="spinner-sm">
                                <button type="button" class="btn btn-icon rounded-circle"><i data-feather="minus"></i></button>
                                <input type="number" class="form-control" value="1" min="1" max="999">
                                <button type="button" class="btn btn-icon rounded-circle"><i data-feather="plus"></i></button>
                            </div>
                            </td>
                            <td class="cart-price text-right">
                            <span class="roboto-condensed bold">$18.56</span>
                            </td>
                            <td class="cart-action nostretch pr-0">
                            <div class="dropdown">
                                <a href="#" class="nav-icon text-secondary dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i data-feather="more-vertical"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                <button class="dropdown-item" type="button"><i data-feather="heart"></i> Move to wishlist</button>
                                <button class="dropdown-item text-danger" type="button"><i data-feather="x"></i> Remove item</button>
                                </div>
                            </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                
                <form class="form-style-1">
                    <h2 class="roboto-condensed text-center">Dados para Entrega</h2>
                    <h6 class="text-muted mb-4 text-center">Insira seus dados para entrega!</h6>
                    <div class="form-row">
                    <div class="form-group col-6">
                        <label for="shippingFirstName">First Name</label>
                        <input type="text" class="form-control" id="shippingFirstName" value="John">
                    </div>
                    <div class="form-group col-6">
                        <label for="shippingLastName">Last Name</label>
                        <input type="text" class="form-control" id="shippingLastName" value="Thor">
                    </div>
                    <div class="form-group col-6">
                        <label for="shippingEmail">Email Address</label>
                        <input type="email" class="form-control" id="shippingEmail" value="john.thor@example.com">
                    </div>
                    <div class="form-group col-6">
                        <label for="shippingPhone">Phone Number</label>
                        <input type="tel" class="form-control" id="shippingPhone" value="1-787-376-1552">
                    </div>
                    </div>
                    <div class="form-row">
                    <div class="form-group col-12">
                        <label for="shippingAddress">Address</label>
                        <input type="text" class="form-control" id="shippingAddress" value="2114  Jadewood Farms">
                    </div>
                    <div class="form-group col-6 col-sm-5">
                        <label for="shippingCountry">Country</label>
                        <select class="form-control custom-select" id="shippingCountry">
                        <option>Choose country</option>
                        <option value="Australia">Australia</option>
                        <option value="Canada">Canada</option>
                        <option value="France">France</option>
                        <option value="Germany">Germany</option>
                        <option value="Switzerland">Switzerland</option>
                        <option value="USA" selected >United States</option>
                        </select>
                    </div>
                    <div class="form-group col-6 col-sm-5">
                        <label for="shippingCity">City</label>
                        <input type="text" class="form-control" id="shippingCity" value="Piscataway, New Jersey">
                    </div>
                    <div class="form-group col-3 col-sm-2">
                        <label for="shippingZip">ZIP Code</label>
                        <input type="number" class="form-control" id="shippingZip" value="08854">
                    </div>
                    </div>
                    <hr>
                    <div class="form-group text-center mt-3 shipping-group">
                    <div class="custom-control custom-radio custom-control-inline">
                        <input type="radio" id="customRadioInline1" name="customRadioInline1" class="custom-control-input">
                        <label class="custom-control-label text-left" for="customRadioInline1">
                        Standard <span class="counter">(FREE)</span>
                        <small class="counter d-block">10-15 Days</small>
                        </label>
                    </div>
                    <div class="custom-control custom-radio custom-control-inline">
                        <input type="radio" id="customRadioInline2" name="customRadioInline1" class="custom-control-input" checked>
                        <label class="custom-control-label text-left" for="customRadioInline2">
                        Express <span class="counter">($10)</span>
                        <small class="counter d-block">1-3 Days</small>
                        </label>
                    </div>
                    </div>
                    <hr>
                </form>

                <form class="form-style-1" id="form-payment">
                    <h2 class="roboto-condensed text-center">Pagamento com Cartão de Crédito</h2>
                    <h6 class="text-muted mb-4 text-center">tenha em mãos o seu Cartão de Crédito!</a></h6>
                    <div class='card-wrapper mb-3'></div>
                    <div class="form-group">
                    <input type="text" name="number" class="form-control" placeholder="Card Number">
                    </div>
                    <div class="form-group">
                    <input type="text" name="name" class="form-control" placeholder="Full Name">
                    </div>
                    <div class="form-row">
                    <div class="form-group col-sm-6">
                        <input type="text" name="expiry" class="form-control" placeholder="Expiry Date">
                    </div>
                    <div class="form-group col-sm-6">
                        <input type="text" name="cvc" class="form-control" placeholder="CVC Code">
                    </div>
                    </div>
                </form>

                <div class="text-center">
                    <small class="counter">SUBTOTAL</small>
                    <h3 class="roboto-condensed bold">R$ 120.00</h3>
                    <a href="shipping.html" class="btn btn-primary rounded-pill btn-lg">ENTREGA <i data-feather="arrow-right"></i></a>
                </div>
            </div>



        </div>

    </div>
    <!-- /Main Content -->

<!-- Footer -->
<?php 
require_once("../templates/public/footer.php"); 
?>
<!-- /Footer -->

<script src="./plugins/jquery/jquery.min.js"></script>
<script src="./plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="./plugins/feather-icons/feather.min.js"></script>
<script src="./plugins/metismenu/metisMenu.min.js"></script>
<script src="./plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script src="./plugins/card/jquery.card.min.js"></script>
<script src="./dist/js/script.min.js"></script>

<script>
    
</script>

<script>
    $(function () {
        $('#form-payment').card({container: '.card-wrapper'})
    });
    
    var AjrcPagSeguro = {
        metodos : [],
        disponivel : [],
        hash : '',
        bandeira: '',
        tokenCartao: '',
        exibeErros: function(response, onde)
        {
            for(var code in response.errors){ console.log("Erro: ",onde," --> ",response.errors[code]) }
        }
    };
</script>
<script src="<?php echo PagSeguro::getUrlJS(); ?>"></script>
<script>

    PagSeguroDirectPayment.setSessionId('<?php  PagSeguro::getSessions(); ?>');
    
    PagSeguroDirectPayment.getPaymentMethods({
        amount: parseFloat(500),
        success: function(response) {

            if(response.paymentMethods.BOLETO){
                AjrcPagSeguro.disponivel.push("BOLETO")
                AjrcPagSeguro.metodos.push(response.paymentMethods.BOLETO.options)
            }

            if(response.paymentMethods.CREDIT_CARD){
                AjrcPagSeguro.disponivel.push("CREDIT_CARD")
                AjrcPagSeguro.metodos.push(response.paymentMethods.CREDIT_CARD.options)
            }
            
            if(response.paymentMethods.ONLINE_DEBIT){
                AjrcPagSeguro.disponivel.push("ONLINE_DEBIT")
                AjrcPagSeguro.metodos.push(response.paymentMethods.ONLINE_DEBIT.options)
            }
            
            console.log(AjrcPagSeguro.metodos, AjrcPagSeguro.disponivel)
        },
        error: function(response) {
            AjrcPagSeguro.exibeErros(response, "PagSeguroDirectPayment.getPaymentMethods")
        }
    });

    PagSeguroDirectPayment.onSenderHashReady(function(response){
        if(response.status == 'error') {
            console.log(response.message);
            return false;
        }
        var hash = response.senderHash; //Hash estará disponível nesta variável.
        AjrcPagSeguro.hash = hash;
        //console.log(AjrcPagSeguro.hash, "--> ",response.status)
    });

    //UTILIZADO SOMENTE COM CARTÃO DE CRÉDITO: DETECTA A BANDEIRA E SUAS REGRAS
    PagSeguroDirectPayment.getBrand({
        cardBin: 411111,
        success: function(response) {
            //bandeira encontrada
            //console.log(response)
            AjrcPagSeguro.bandeira.push(response.brand)
        },
        error: function(response) {
        //tratamento do erro
        },
        complete: function(response) {
        //tratamento comum para todas chamadas
        }
    });
    /*
    //UTILIZADO SOMENTE COM CARTÃO DE CRÉDITO: DETECTA QTDE DE PAGTOS
    PagSeguroDirectPayment.getInstallments({
        amount: parseFloat(118.80),
        maxInstallmentNoInterest: 3,
        //brand: 'visa',
        brand:'mastercard',
        success: function(response){
            console.log(response)
       	    // Retorna as opções de parcelamento disponíveis
       },
        error: function(response) {
       	    // callback para chamadas que falharam.
       },
        complete: function(response){
            // Callback para todas chamadas.
       }
    });
    //*/
</script>