<?php

use Ajrc\Helper\Sessions;
use Ajrc\Helper\AlertBootstrap4 as Alert;
use Ajrc\Model\Destaque;
use Ajrc\Model\Produto;

$P = Produto::List($data["id"]);
$estoque = $P->qtde_atual;

// SEO : SEARCH ENGINE OPTIMIZATE ----
$title = $P->titulo ." -  Por apenas R\$".number_format($P->preco_venda,2,',','.') . " - Chokoart! ";
$description = $title . $P->descritivo;
$url_redirect = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
//----

$mais_imagens = null;
$pasta_imagens = "img/produtos/";
$contador = 0;
$url_img_1 = null;
$checked = null;
foreach (glob($pasta_imagens . $P->id."_*") as $fotos) 
{
    if($contador==0){ $url_img_1 = $fotos; $checked = " checked"; }
    $mais_imagens.=  '<img src="'.$fotos.'" data-large=".'.$fotos.'" alt="'.$title.'" class="swiper-slide swiper-slide-active" data-swiper-slide-index="0" style="width: 442px;">';
    $contador++;
}

require_once("../templates/public/header.php");
require_once("../templates/public/topo.php");

?>

<!-- Main Content -->


<div class="container mt-3">

      <!-- Shop Toolbar -->
      <div class="card mb-3">
        <div class="card-body d-flex justify-content-end align-items-center py-2">
          <ol class="breadcrumb d-none d-md-flex p-0 mb-0 mr-auto">
            <li class="breadcrumb-item"><a href="./">Página Principal</a></li>
            <li class="breadcrumb-item"><a href="./categoria-<?php echo $P->categoria_id; ?>--<?php echo str_replace(" ","-",$P->categoria); ?>"><?php echo $P->categoria; ?></a></li>
            <li class="breadcrumb-item active" aria-current="page"><?php echo $P->titulo; ?></li>
          </ol>
          <span class="text-muted mr-1">Compartilhe:</span>
          <a href="https://www.facebook.com/sharer.php?u=<?php echo $url_redirect; ?>" class="btn btn-icon rounded-pill btn-sm btn-outline-primary ml-1" data-toggle="tooltip" target="_blank" title="no Facebook"><i data-feather="facebook"></i></a>
          <a href="http://twitter.com/intent/tweet?text=<?php echo $title;?>&url=<?php echo $url_redirect; ?>&via=@chokoart.com" class="btn btn-icon rounded-pill btn-sm btn-outline-primary ml-1" data-toggle="tooltip" target="_blank" title="no Twitter"><i data-feather="twitter"></i></i></a>
        </div>
      </div>
      <!-- /Shop Toolbar -->

      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">

                <div class="swiper-container swiper-container-initialized swiper-container-horizontal" id="product-slider">
                    <div class="swiper-wrapper" style="transition-duration: 0ms; transform: translate3d(-442px, 0px, 0px);">
                        <?php echo $mais_imagens; ?>
                    </div>
                    <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"><span class="swiper-pagination-bullet swiper-pagination-bullet-active" tabindex="0" role="button" aria-label="Go to slide 1"></span><span class="swiper-pagination-bullet" tabindex="0" role="button" aria-label="Go to slide 2"></span><span class="swiper-pagination-bullet" tabindex="0" role="button" aria-label="Go to slide 3"></span></div>
                    <div class="swiper-button-prev autohide" tabindex="0" role="button" aria-label="Previous slide"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left"><polyline points="15 18 9 12 15 6"></polyline></svg></div>
                    <div class="swiper-button-next autohide" tabindex="0" role="button" aria-label="Next slide"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right"><polyline points="9 18 15 12 9 6"></polyline></svg></div>
                    <button class="wishlist atw-demo" style="width:58px;height:58px;" id="<?php echo $P->id; ?>" data-value="<?php echo $P->preco_venda; ?>" title="Adicionar a sua Lista de Desejos!"><svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" class="feather feather-heart"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg></button>
                </div>
              <hr>
              <form method="POST" action="./cart">
              <input type="hidden" name="passo" value="0">
              <input type="hidden" name="produto_id"  value="<?php echo $P->id; ?>">
              <input type="hidden" name="titulo" value="<?php echo $P->titulo; ?>">
              <input type="hidden" name="qtde_estoque" id="qtde_estoque-<?php echo $P->id; ?>" value="<?php echo $P->qtde_atual; ?>">
              <input type="hidden" name="preco_unit_item" id="preco_unit_item-<?php echo $P->id; ?>" value="<?php echo $P->preco_venda; ?>">
              <input type="hidden" name="preco_total_item" id="preco_total_item-<?php echo $P->id; ?>" value="<?php echo $P->preco_venda; ?>">
              <input type="hidden" name="valor_total_pedido" id="valor_total_pedido" value="<?php echo $P->preco_venda; ?>">
                <div class="form-row">
                  <div class="form-group col-6">
                    <label class="bold">Quantidade</label>
                    <div class="w-100 spinner">
                      <button id="btnMenos-<?php echo $P->id; ?>" type="button" class="btn btn-icon rounded-circle menos"><i data-feather="minus"></i></button>
                      <input id="qtde-<?php echo $P->id; ?>" name="qtde" type="number" class="form-control" value="1" min="0" max="999">
                      <button id="btnMais-<?php echo $P->id; ?>" type="button" class="btn btn-icon rounded-circle mais"><i data-feather="plus"></i></button>
                    </div>

                  </div>
                  <div class="form-group col-6 d-flex align-items-end">
                    <button type="submit" class="btn btn-primary btn-block rounded-pill">Adicionar ao  <i data-feather="shopping-cart"></i></button>
                  </div>
                </div>
              </form>
              <hr>
            </div>
            <div class="col-md-6 mt-3 mt-md-0">
                <h3 class="card-title"><?php echo $P->titulo; ?></h3>
                <hr style="border-top: dotted 1px">
                <div class="d-flex justify-content-start">Avaliação de nosso clientes: <strong class="ml-1">4.5</strong> <span class="rating ml-2" data-value="4.5"></span> </div>
                <hr>
                <h2 class="price text-left"><span>R$ <?php echo number_format($P->preco_venda,2,',','.'); ?></span></h2>
                <hr style="border-top: dotted 1px">
                <p class=""><?php echo nl2br($P->descritivo); ?></p>
                
              <div class="d-flex align-items-center">
                <span class="text-muted">Compartilhe </span>
                <a  href="https://www.facebook.com/sharer.php?u=<?php echo $url_redirect; ?>" target="_blank" title="Compartilhar no Facebook" class="btn btn-light btn-icon rounded-circle border ml-2" data-toggle="tooltip" data-original-title="Facebook"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg></a>
                <a href="http://twitter.com/intent/tweet?text=<?php echo $title;?>&url=<?php echo $url_redirect; ?>&via=@chokoart.com" class="btn btn-light btn-icon rounded-circle border ml-2" data-toggle="tooltip" title="" data-original-title="Twitter"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg></a>
              </div>
            </div>
          </div>
        </div>
        <div class="card-header bg-white border-bottom flex-center p-0 mt-3">
          <ul class="nav nav-pills card-header-pills main-nav-pills" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" id="reviews" data-toggle="tab" href="#review-content" role="tab" aria-controls="review-content" aria-selected="false">REVIEWS (2)</a>
            </li>
          </ul>
        </div>
        <div class="tab-content">
          
          <div class="card-body tab-pane fade show active" id="review-content" role="tabpanel" aria-labelledby="reviews">
            <div class="row gutters-3 justify-content-center">
              <div class="col-11 col-sm-6 col-md-4 col-lg-3">
                <h5 class="bold roboto-condensed rating">
                  OVERALL RATING: 4.5<br><span class="rating" data-value="4.5"></span> 
                </h5>
                <div class="list-group">
                  <a href="javascript:void(0)" class="list-group-item list-group-item-action text-muted d-flex justify-content-between">
                  <span class="rating" data-value="5"></span> <span>1 review </span></a>
                  
                </div>
                <div class="text-center mt-1">
                  <button class="btn btn-primary btn-block rounded-pill" data-toggle="modal" data-target="#reviewModal">Write a review</button>
                </div>
              </div>
              <div class="col-md-8 col-lg-9 mt-5 mt-md-0">
                <div class="media">
                  <a href="javascript:void(0)"><img src="../img/user/user1.svg" alt="User" width="45" height="45" class="rounded-circle"></a>
                  <div class="media-body ml-2 ml-sm-3">
                    <h6 class="bold">Terrific Shirt, Exactly What I Wanted.</h6>
                    <p class="d-flex flex-wrap">
                      <span class="rating mr-2" data-value="5"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 32 32"><title>star-full</title><path d="M32 12.408l-11.056-1.607-4.944-10.018-4.944 10.018-11.056 1.607 8 7.798-1.889 11.011 9.889-5.199 9.889 5.199-1.889-11.011 8-7.798z"></path></svg>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 32 32"><title>star-full</title><path d="M32 12.408l-11.056-1.607-4.944-10.018-4.944 10.018-11.056 1.607 8 7.798-1.889 11.011 9.889-5.199 9.889 5.199-1.889-11.011 8-7.798z"></path></svg>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 32 32"><title>star-full</title><path d="M32 12.408l-11.056-1.607-4.944-10.018-4.944 10.018-11.056 1.607 8 7.798-1.889 11.011 9.889-5.199 9.889 5.199-1.889-11.011 8-7.798z"></path></svg>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 32 32"><title>star-full</title><path d="M32 12.408l-11.056-1.607-4.944-10.018-4.944 10.018-11.056 1.607 8 7.798-1.889 11.011 9.889-5.199 9.889 5.199-1.889-11.011 8-7.798z"></path></svg>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 32 32"><title>star-full</title><path d="M32 12.408l-11.056-1.607-4.944-10.018-4.944 10.018-11.056 1.607 8 7.798-1.889 11.011 9.889-5.199 9.889 5.199-1.889-11.011 8-7.798z"></path></svg>
</span>
                      <a href="javascript:void(0)" class="mr-2">Alan Lewis</a>
                      <span class="text-muted">3 days ago</span>
                    </p>
                    <p>The Hanes sweatshirt was precisely what I wanted except for the color which is better than what I thought I was getting. This order went perfectly, so much so that another two are being shipped to me right now. It is way too early to say anything about durability; but otherwise, there is no way this order could have gone any better than it did. If you are interested in a pretty traditional long-sleeve sweatshirt, you would do well to give this one serious consideration.</p>
                    <hr>
                  </div>
                </div>
                <div class="media">
                  <a href="javascript:void(0)"><img src="../img/user/user2.svg" alt="User" width="45" height="45" class="rounded-circle"></a>
                  <div class="media-body ml-2 ml-sm-3">
                    <h6 class="bold">Very comfortable.</h6>
                    <p class="d-flex flex-wrap">
                      <span class="rating mr-2" data-value="4"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 32 32"><title>star-full</title><path d="M32 12.408l-11.056-1.607-4.944-10.018-4.944 10.018-11.056 1.607 8 7.798-1.889 11.011 9.889-5.199 9.889 5.199-1.889-11.011 8-7.798z"></path></svg>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 32 32"><title>star-full</title><path d="M32 12.408l-11.056-1.607-4.944-10.018-4.944 10.018-11.056 1.607 8 7.798-1.889 11.011 9.889-5.199 9.889 5.199-1.889-11.011 8-7.798z"></path></svg>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 32 32"><title>star-full</title><path d="M32 12.408l-11.056-1.607-4.944-10.018-4.944 10.018-11.056 1.607 8 7.798-1.889 11.011 9.889-5.199 9.889 5.199-1.889-11.011 8-7.798z"></path></svg>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 32 32"><title>star-full</title><path d="M32 12.408l-11.056-1.607-4.944-10.018-4.944 10.018-11.056 1.607 8 7.798-1.889 11.011 9.889-5.199 9.889 5.199-1.889-11.011 8-7.798z"></path></svg>
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 32 32"><title>star-empty</title><path d="M32 12.408l-11.056-1.607-4.944-10.018-4.944 10.018-11.056 1.607 8 7.798-1.889 11.011 9.889-5.199 9.889 5.199-1.889-11.011 8-7.798zM16 23.547l-6.983 3.671 1.334-7.776-5.65-5.507 7.808-1.134 3.492-7.075 3.492 7.075 7.807 1.134-5.65 5.507 1.334 7.776-6.983-3.671z"></path></svg>
</span>
                      <a href="javascript:void(0)" class="mr-2">Amy</a>
                      <span class="text-muted">5 days ago</span>
                    </p>
                    <p>Fits slightly larger than expected, but gets longer, not just wider. (For reference, I am female, 5'8'', 170lbs, and this sweatshirt fits around my 36J chest with room to spare, coming to rest at about crotch level)</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Related Products -->
      <h4 class="bold text-center mt-gutter">Produtos Relacionados</h4>
      <div class="grid grid-gap-3 grid-col-2 grid-col-md-4 my-3">
            <?php Produto::GetPublicRelationed($P->id, $P->categoria_id); ?>
      </div>
      <!-- /Related Products -->

    </div>
<!-- /Main Content -->

<!-- Add review modal -->
<div class="modal fade" tabindex="-1" role="dialog" id="reviewModal">
      <div class="modal-dialog" role="document">
        <div class="modal-content bg-light">
          <div class="modal-header">
            <h5 class="modal-title">Deixe uma avaliação</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form class="form-style-1">
              
              <div class="form-group">
                <label for="reviewRating">Na sua opinião, merece quantas estrelas?</label>
                <select class="form-control bg-white custom-select" id="reviewRating">
                  <option value="5.0">5 Estrelas</option>
                  <option value="4.0">4 Estrelas</option>
                  <option value="3.0">3 Estrelas</option>
                  <option value="2.0">2 Estrelas</option>
                  <option value="1.0">1 Estrela</option>
                </select>
              </div>
              <div class="form-group">
                <label for="reviewText">Escreva sua opinião</label>
                <textarea class="form-control bg-white" id="reviewText" rows="5"></textarea>
              </div>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn rounded-pill btn-secondary" data-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn rounded-pill btn-primary">Enviar</button>
          </div>
        </div>
      </div>
    </div>
    <!-- /Add review modal -->

    


<!-- Footer -->
<?php 
require_once("../templates/public/footer.php"); 
?>
<!-- /Footer -->


    <script src="plugins/jquery/jquery.min.js"></script>
    <script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="plugins/feather-icons/feather.min.js"></script>
    <script src="plugins/metismenu/metisMenu.min.js"></script>
    <script src="plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="plugins/swiper/swiper.min.js"></script>
    <script src="plugins/photoswipe/photoswipe.min.js"></script>
    <script src="plugins/photoswipe/photoswipe-ui-default.min.js"></script>
    <script src="plugins/noty/noty.min.js"></script>
    <script src="dist/js/script.min.js"></script>
    <script src="js/produto.js"></script>
    <script>
    $(function () {

      App.rating()
      App.atwDemo()
      App.colorOption()

      setTimeout(function (argument) {
        var productSlider = new Swiper('#product-slider', {
          loop: true,
          pagination: {
            el: '.swiper-pagination',
            clickable: true
          },
          navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
          }
        })
      }, 100)

      // Collect items for photoswipe
      var items = []
      $('.swiper-wrapper img').each(function () {
        items.push({
          src: $(this).data('large'),
          w: 1395,
          h: 1500
        })
      })

      var openPhotoSwipe = function (items, activeIndex) {
        activeIndex = typeof activeIndex !== 'undefined' ? activeIndex : 0
        var pswpElement = document.querySelectorAll('.pswp')[0]
        var options = {
          index: activeIndex
        }
        var gallery = new PhotoSwipe(pswpElement, PhotoSwipeUI_Default, items, options)
        gallery.init()
      }

      $('.zoom').click(function () {
        openPhotoSwipe(items, $('.swiper-wrapper').find('.swiper-slide-active').data('swiper-slide-index'))
      })

      <?php
        if(Sessions::UserID()!="") { 
            echo "WishList.Persistence('../add-whislist');"; 
        }
        ?>

    })
    </script>




</body>
</html>
